#!/bin/bash

#only continue if the server is reachable
statuscheck=`ssh hb 2>&1`
if [[ $statuscheck == *onnect* ]]; then
	exit 1
fi

#backs up commonly modified files
for f in `cat ~/.config/datasync/files`; do
	rt=`ssh hb "date -r ~/img +%s"`
	lt=`date -r ~/img +%s`
	if [[ ${lt} != ${rt} && ${lt} -ge ${rt} ]]; then #local file is newer, so update
		f=`echo ${f} | sed 's,~,/home/'${USER}',g'`
		echo $f
		backup_simple ${f} ${f}
	fi
done
