#!/bin/bash
#Words Of Wisdom
# output some random text from my journal 

r=5
if [[ $1 ]]; then
	r=$1
fi

files=(~/_journal ~/_poetry ~/doc/_journal_2019) #TODO other files
if [[ $1 == "-o" ]]; then
	files+=("~/doc/daily-writings/comp")
fi
n=${#files[@]}
n=$(($n-1))
f=${files[`shuf -i 0-${n} -n 1`]}
l=`wc -l ${f} | cut -f1 -d' '`
t=''
while [[ ! "$t" =~ ^[a-zA-Z0-9] || "$t" =~ ^[0-9] ]]; do 
	i=`shuf -i 0-${l} -n 1`
	s=$(($i-$r))
	e=$(($i+$r))
	cmd="sed -n ${s},${e}p ${f}"
	t=`$cmd`
done
echo ${t}
